//! Content blocks for Messages API requests, responses, and streaming.
//!
//! Two parallel block taxonomies live here because the Messages API uses
//! slightly different shapes on the request and response sides:
//!
//! - [`ContentBlockParam`] is the **request-side** tagged union: text,
//!   image (base64 / URL), document (base64 / URL / text / nested
//!   content), search-result, tool-use replay, tool-result, thinking, and
//!   redacted-thinking. Every variant that the API supports carries an
//!   optional [`crate::CacheControl`].
//! - [`ContentBlock`] is the **response-side** tagged union returned in
//!   [`crate::Message::content`], including typed citation arrays on text
//!   blocks.
//!
//! Sources for image and document blocks are typed
//! ([`ImageSourceParam`], [`DocumentSourceParam`], [`DocumentMediaType`],
//! [`ContentBlockSourceContentParam`],
//! [`ContentBlockSourceContentBlockParam`]) rather than raw JSON.
//! [`SearchResultTextBlockParam`] models text-only search-result content.
//!
//! Citations on both sides ([`TextCitation`] /
//! [`TextCitationParam`]) cover `char_location`, `page_location`,
//! `content_block_location`, `web_search_result_location`, and
//! `search_result_location`.
//!
//! [`ToolUse`] is a borrowed view returned by
//! [`crate::Message::tool_uses`], paired with
//! [`ToolInputDecodeError`] for typed input decoding that does **not**
//! leak raw tool-input JSON in `Display`.
//!
//! [`ContentBlockParamConversionError`] and
//! [`ContentBlockParamCacheControlError`] surface the validation failures
//! that builders apply at the request boundary.

use serde::{Deserialize, Serialize, de::DeserializeOwned};
use thiserror::Error;

use crate::{CacheControl, ToolName, ToolNameError};

/// A content block returned by the API.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlock {
    /// Plain text content.
    Text {
        /// The UTF-8 text payload.
        text: String,
        /// Citations supporting this text block, when returned by the API.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        citations: Option<Vec<TextCitation>>,
    },
    /// Extended thinking content returned by the model.
    Thinking {
        /// The model's thinking text.
        thinking: String,
        /// Signature used by the API for multi-turn thinking continuity, when present.
        #[serde(skip_serializing_if = "Option::is_none")]
        signature: Option<String>,
    },
    /// Redacted extended thinking content returned by the model.
    RedactedThinking {
        /// Opaque redacted thinking payload.
        data: String,
    },
    /// A model tool-use request.
    ToolUse {
        /// API-generated tool-use identifier.
        id: String,
        /// Tool name requested by the model.
        name: String,
        /// JSON input for the selected tool.
        input: serde_json::Value,
    },
    /// A tool result supplied back to the model.
    ToolResult {
        /// Identifier of the tool-use block this result answers.
        tool_use_id: String,
        /// Result content blocks.
        content: Vec<ContentBlock>,
    },
}

impl ContentBlock {
    /// Creates a text content block.
    pub fn text(text: impl Into<String>) -> Self {
        Self::Text {
            text: text.into(),
            citations: None,
        }
    }

    /// Creates a thinking content block without a signature.
    pub fn thinking(thinking: impl Into<String>) -> Self {
        Self::Thinking {
            thinking: thinking.into(),
            signature: None,
        }
    }

    /// Creates a redacted thinking content block.
    pub fn redacted_thinking(data: impl Into<String>) -> Self {
        Self::RedactedThinking { data: data.into() }
    }

    /// Returns this block as a borrowed tool-use view when it is a tool-use block.
    pub fn as_tool_use(&self) -> Option<ToolUse<'_>> {
        match self {
            Self::ToolUse { id, name, input } => Some(ToolUse { id, name, input }),
            _ => None,
        }
    }
}

/// Borrowed view over a response `tool_use` content block.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ToolUse<'a> {
    id: &'a str,
    name: &'a str,
    input: &'a serde_json::Value,
}

impl<'a> ToolUse<'a> {
    /// Returns the API-generated tool-use identifier.
    pub fn id(&self) -> &'a str {
        self.id
    }

    /// Returns the requested tool name.
    pub fn name(&self) -> &'a str {
        self.name
    }

    /// Returns the raw JSON input generated by the model.
    pub fn input(&self) -> &'a serde_json::Value {
        self.input
    }

    /// Decodes the tool input into a caller-owned type.
    ///
    /// The returned error keeps the serde source error but its display text does
    /// not include the raw input JSON.
    pub fn decode_input<T>(&self) -> Result<T, ToolInputDecodeError>
    where
        T: DeserializeOwned,
    {
        serde_json::from_value(self.input.clone()).map_err(|source| {
            ToolInputDecodeError::Deserialize {
                tool_use_id: self.id.to_owned(),
                name: self.name.to_owned(),
                source,
            }
        })
    }

    /// Creates a text tool-result block answering this tool use.
    pub fn tool_result(&self, content: impl Into<String>) -> ContentBlockParam {
        ContentBlockParam::tool_result(self.id, content)
    }

    /// Creates a text error tool-result block answering this tool use.
    pub fn tool_result_error(&self, content: impl Into<String>) -> ContentBlockParam {
        ContentBlockParam::tool_result_error(self.id, content)
    }

    /// Creates a structured tool-result block answering this tool use.
    pub fn tool_result_blocks(&self, content: Vec<ContentBlockParam>) -> ContentBlockParam {
        ContentBlockParam::tool_result_blocks(self.id, content)
    }

    /// Creates a structured tool-result block with explicit error status.
    pub fn tool_result_blocks_with_error(
        &self,
        content: Vec<ContentBlockParam>,
        is_error: bool,
    ) -> ContentBlockParam {
        ContentBlockParam::tool_result_blocks_with_error(self.id, content, is_error)
    }
}

/// Errors produced while decoding a response tool-use input.
#[derive(Debug, Error)]
pub enum ToolInputDecodeError {
    /// The tool input could not be deserialized into the requested type.
    #[error("failed to decode input for tool `{name}`")]
    Deserialize {
        /// API-generated tool-use identifier.
        tool_use_id: String,
        /// Tool name requested by the model.
        name: String,
        /// Serde decoding error.
        #[source]
        source: serde_json::Error,
    },
}

/// A content block accepted in message creation parameters.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlockParam {
    /// Plain text content.
    Text {
        /// The UTF-8 text payload.
        text: String,
        /// Optional citations attached to this text block.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        citations: Option<Vec<TextCitationParam>>,
        /// Optional cache control marker for this text block.
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<CacheControl>,
    },
    /// Image content supplied by the caller.
    Image {
        /// The image source.
        source: ImageSourceParam,
        /// Optional cache control marker for this image block.
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<CacheControl>,
    },
    /// Document content supplied by the caller.
    Document {
        /// The document source.
        source: DocumentSourceParam,
        /// Optional title for the document.
        #[serde(skip_serializing_if = "Option::is_none")]
        title: Option<String>,
        /// Optional context that helps the model interpret the document.
        #[serde(skip_serializing_if = "Option::is_none")]
        context: Option<String>,
        /// Optional citation configuration for the document.
        #[serde(skip_serializing_if = "Option::is_none")]
        citations: Option<CitationsConfigParam>,
        /// Optional cache control marker for this document block.
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<CacheControl>,
    },
    /// Search result content supplied by the caller.
    SearchResult {
        /// Text blocks that make up the search result body.
        content: Vec<SearchResultTextBlockParam>,
        /// Source URL or identifier for the result.
        source: String,
        /// Search result title.
        title: String,
        /// Optional citation configuration for the search result.
        #[serde(skip_serializing_if = "Option::is_none")]
        citations: Option<CitationsConfigParam>,
        /// Optional cache control marker for this search result block.
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<CacheControl>,
    },
    /// Extended thinking content supplied back for multi-turn continuity.
    Thinking {
        /// The model's thinking text.
        thinking: String,
        /// Signature used by the API for multi-turn thinking continuity, when present.
        #[serde(skip_serializing_if = "Option::is_none")]
        signature: Option<String>,
    },
    /// Redacted extended thinking content supplied back for multi-turn continuity.
    RedactedThinking {
        /// Opaque redacted thinking payload.
        data: String,
    },
    /// A model tool-use request supplied back for conversation replay.
    ToolUse {
        /// API-generated tool-use identifier.
        id: String,
        /// Tool name requested by the model.
        name: ToolName,
        /// JSON input for the selected tool.
        input: serde_json::Value,
        /// Optional cache control marker for this tool-use replay block.
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<CacheControl>,
    },
    /// A tool result supplied by the caller.
    ToolResult {
        /// Identifier of the tool-use block this result answers.
        tool_use_id: String,
        /// Whether the tool call failed.
        #[serde(skip_serializing_if = "Option::is_none")]
        is_error: Option<bool>,
        /// Result content blocks.
        content: ToolResultContent,
        /// Optional cache control marker for this tool-result block.
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<CacheControl>,
    },
}

impl ContentBlockParam {
    /// Creates a text content parameter.
    pub fn text(text: impl Into<String>) -> Self {
        Self::Text {
            text: text.into(),
            citations: None,
            cache_control: None,
        }
    }

    /// Creates a text content parameter with citations.
    pub fn text_with_citations(text: impl Into<String>, citations: Vec<TextCitationParam>) -> Self {
        Self::Text {
            text: text.into(),
            citations: Some(citations),
            cache_control: None,
        }
    }

    /// Creates a text content parameter with a cache-control marker.
    pub fn text_with_cache_control(text: impl Into<String>, cache_control: CacheControl) -> Self {
        Self::Text {
            text: text.into(),
            citations: None,
            cache_control: Some(cache_control),
        }
    }

    /// Creates a base64 image content parameter.
    pub fn image_base64(media_type: impl Into<String>, data: impl Into<String>) -> Self {
        Self::Image {
            source: ImageSourceParam::base64(media_type, data),
            cache_control: None,
        }
    }

    /// Creates a URL image content parameter.
    pub fn image_url(url: impl Into<String>) -> Self {
        Self::Image {
            source: ImageSourceParam::url(url),
            cache_control: None,
        }
    }

    /// Creates a base64 PDF document content parameter.
    pub fn document_base64_pdf(data: impl Into<String>) -> Self {
        Self::document(DocumentSourceParam::base64_pdf(data))
    }

    /// Creates a plain text document content parameter.
    pub fn document_text(data: impl Into<String>) -> Self {
        Self::document(DocumentSourceParam::plain_text(data))
    }

    /// Creates a URL PDF document content parameter.
    pub fn document_url(url: impl Into<String>) -> Self {
        Self::document(DocumentSourceParam::url_pdf(url))
    }

    /// Creates a document content parameter from typed document source content.
    pub fn document_content(content: ContentBlockSourceContentParam) -> Self {
        Self::document(DocumentSourceParam::content(content))
    }

    /// Creates a document content parameter from an explicit source.
    pub fn document(source: DocumentSourceParam) -> Self {
        Self::Document {
            source,
            title: None,
            context: None,
            citations: None,
            cache_control: None,
        }
    }

    /// Creates a search result content parameter.
    pub fn search_result(
        content: Vec<SearchResultTextBlockParam>,
        source: impl Into<String>,
        title: impl Into<String>,
    ) -> Self {
        Self::SearchResult {
            content,
            source: source.into(),
            title: title.into(),
            citations: None,
            cache_control: None,
        }
    }

    /// Creates a thinking content parameter without a signature.
    pub fn thinking(thinking: impl Into<String>) -> Self {
        Self::Thinking {
            thinking: thinking.into(),
            signature: None,
        }
    }

    /// Creates a thinking content parameter with a signature.
    pub fn thinking_with_signature(
        thinking: impl Into<String>,
        signature: impl Into<String>,
    ) -> Self {
        Self::Thinking {
            thinking: thinking.into(),
            signature: Some(signature.into()),
        }
    }

    /// Creates a redacted thinking content parameter.
    pub fn redacted_thinking(data: impl Into<String>) -> Self {
        Self::RedactedThinking { data: data.into() }
    }

    /// Creates a tool-use content parameter for assistant message replay.
    pub fn tool_use(
        id: impl Into<String>,
        name: impl TryInto<ToolName, Error = ToolNameError>,
        input: serde_json::Value,
    ) -> Result<Self, ToolNameError> {
        Ok(Self::ToolUse {
            id: id.into(),
            name: name.try_into()?,
            input,
            cache_control: None,
        })
    }

    /// Creates a text tool result content block.
    pub fn tool_result(tool_use_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self::ToolResult {
            tool_use_id: tool_use_id.into(),
            is_error: None,
            content: ToolResultContent::text(content),
            cache_control: None,
        }
    }

    /// Creates a text tool result content block that represents a tool failure.
    pub fn tool_result_error(tool_use_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self::ToolResult {
            tool_use_id: tool_use_id.into(),
            is_error: Some(true),
            content: ToolResultContent::text(content),
            cache_control: None,
        }
    }

    /// Creates a structured tool result content block.
    pub fn tool_result_blocks(
        tool_use_id: impl Into<String>,
        content: Vec<ContentBlockParam>,
    ) -> Self {
        Self::ToolResult {
            tool_use_id: tool_use_id.into(),
            is_error: None,
            content: ToolResultContent::blocks(content),
            cache_control: None,
        }
    }

    /// Creates a structured tool result content block with explicit error status.
    pub fn tool_result_blocks_with_error(
        tool_use_id: impl Into<String>,
        content: Vec<ContentBlockParam>,
        is_error: bool,
    ) -> Self {
        Self::ToolResult {
            tool_use_id: tool_use_id.into(),
            is_error: Some(is_error),
            content: ToolResultContent::blocks(content),
            cache_control: None,
        }
    }

    /// Sets cache control on a cacheable request content block.
    pub fn with_cache_control(
        self,
        cache_control: CacheControl,
    ) -> Result<Self, ContentBlockParamCacheControlError> {
        match self {
            Self::Text {
                text, citations, ..
            } => Ok(Self::Text {
                text,
                citations,
                cache_control: Some(cache_control),
            }),
            Self::Image { source, .. } => Ok(Self::Image {
                source,
                cache_control: Some(cache_control),
            }),
            Self::Document {
                source,
                title,
                context,
                citations,
                ..
            } => Ok(Self::Document {
                source,
                title,
                context,
                citations,
                cache_control: Some(cache_control),
            }),
            Self::SearchResult {
                content,
                source,
                title,
                citations,
                ..
            } => Ok(Self::SearchResult {
                content,
                source,
                title,
                citations,
                cache_control: Some(cache_control),
            }),
            Self::ToolUse {
                id, name, input, ..
            } => Ok(Self::ToolUse {
                id,
                name,
                input,
                cache_control: Some(cache_control),
            }),
            Self::ToolResult {
                tool_use_id,
                is_error,
                content,
                ..
            } => Ok(Self::ToolResult {
                tool_use_id,
                is_error,
                content,
                cache_control: Some(cache_control),
            }),
            Self::Thinking { .. } => Err(
                ContentBlockParamCacheControlError::UnsupportedContentBlock {
                    block_type: "thinking",
                },
            ),
            Self::RedactedThinking { .. } => Err(
                ContentBlockParamCacheControlError::UnsupportedContentBlock {
                    block_type: "redacted_thinking",
                },
            ),
        }
    }
}

/// A citation attached to a response text block.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum TextCitation {
    /// Citation into a plain text document by character offsets.
    #[serde(rename = "char_location")]
    Char {
        /// Text cited by the model.
        cited_text: String,
        /// Zero-based index of the cited document block in the request.
        document_index: u32,
        /// Title of the cited document, when available.
        document_title: Option<String>,
        /// End character offset.
        end_char_index: u32,
        /// File identifier for hosted/container-backed documents, when returned.
        file_id: Option<String>,
        /// Start character offset.
        start_char_index: u32,
    },
    /// Citation into a PDF document by page numbers.
    #[serde(rename = "page_location")]
    Page {
        /// Text cited by the model.
        cited_text: String,
        /// Zero-based index of the cited document block in the request.
        document_index: u32,
        /// Title of the cited document, when available.
        document_title: Option<String>,
        /// Ending page number.
        end_page_number: u32,
        /// File identifier for hosted/container-backed documents, when returned.
        file_id: Option<String>,
        /// Starting page number.
        start_page_number: u32,
    },
    /// Citation into a content-document source by content-block offsets.
    #[serde(rename = "content_block_location")]
    ContentBlock {
        /// Text cited by the model.
        cited_text: String,
        /// Zero-based index of the cited document block in the request.
        document_index: u32,
        /// Title of the cited document, when available.
        document_title: Option<String>,
        /// End content-block index.
        end_block_index: u32,
        /// File identifier for hosted/container-backed documents, when returned.
        file_id: Option<String>,
        /// Start content-block index.
        start_block_index: u32,
    },
    /// Citation into a web-search result.
    #[serde(rename = "web_search_result_location")]
    WebSearchResult {
        /// Text cited by the model.
        cited_text: String,
        /// Opaque encrypted search-result index.
        encrypted_index: String,
        /// Title of the cited result, when available.
        title: Option<String>,
        /// URL of the cited result.
        url: String,
    },
    /// Citation into a request `search_result` block.
    #[serde(rename = "search_result_location")]
    SearchResult {
        /// Text cited by the model.
        cited_text: String,
        /// End content-block index inside the search result.
        end_block_index: u32,
        /// Zero-based index of the cited search-result block in the request.
        search_result_index: u32,
        /// Source URL or identifier for the cited search result.
        source: String,
        /// Start content-block index inside the search result.
        start_block_index: u32,
        /// Title of the cited result, when available.
        title: Option<String>,
    },
}

impl TextCitation {
    /// Converts this response citation into a request citation parameter.
    pub fn into_param(self) -> TextCitationParam {
        match self {
            Self::Char {
                cited_text,
                document_index,
                document_title,
                end_char_index,
                file_id: _,
                start_char_index,
            } => TextCitationParam::Char {
                cited_text,
                document_index,
                document_title,
                end_char_index,
                start_char_index,
            },
            Self::Page {
                cited_text,
                document_index,
                document_title,
                end_page_number,
                file_id: _,
                start_page_number,
            } => TextCitationParam::Page {
                cited_text,
                document_index,
                document_title,
                end_page_number,
                start_page_number,
            },
            Self::ContentBlock {
                cited_text,
                document_index,
                document_title,
                end_block_index,
                file_id: _,
                start_block_index,
            } => TextCitationParam::ContentBlock {
                cited_text,
                document_index,
                document_title,
                end_block_index,
                start_block_index,
            },
            Self::WebSearchResult {
                cited_text,
                encrypted_index,
                title,
                url,
            } => TextCitationParam::WebSearchResult {
                cited_text,
                encrypted_index,
                title,
                url,
            },
            Self::SearchResult {
                cited_text,
                end_block_index,
                search_result_index,
                source,
                start_block_index,
                title,
            } => TextCitationParam::SearchResult {
                cited_text,
                end_block_index,
                search_result_index,
                source,
                start_block_index,
                title,
            },
        }
    }
}

impl From<TextCitation> for TextCitationParam {
    fn from(value: TextCitation) -> Self {
        value.into_param()
    }
}

/// A citation accepted on a request text block.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum TextCitationParam {
    /// Citation into a plain text document by character offsets.
    #[serde(rename = "char_location")]
    Char {
        /// Text cited by the model.
        cited_text: String,
        /// Zero-based index of the cited document block in the request.
        document_index: u32,
        /// Title of the cited document, when available.
        #[serde(skip_serializing_if = "Option::is_none")]
        document_title: Option<String>,
        /// End character offset.
        end_char_index: u32,
        /// Start character offset.
        start_char_index: u32,
    },
    /// Citation into a PDF document by page numbers.
    #[serde(rename = "page_location")]
    Page {
        /// Text cited by the model.
        cited_text: String,
        /// Zero-based index of the cited document block in the request.
        document_index: u32,
        /// Title of the cited document, when available.
        #[serde(skip_serializing_if = "Option::is_none")]
        document_title: Option<String>,
        /// Ending page number.
        end_page_number: u32,
        /// Starting page number.
        start_page_number: u32,
    },
    /// Citation into a content-document source by content-block offsets.
    #[serde(rename = "content_block_location")]
    ContentBlock {
        /// Text cited by the model.
        cited_text: String,
        /// Zero-based index of the cited document block in the request.
        document_index: u32,
        /// Title of the cited document, when available.
        #[serde(skip_serializing_if = "Option::is_none")]
        document_title: Option<String>,
        /// End content-block index.
        end_block_index: u32,
        /// Start content-block index.
        start_block_index: u32,
    },
    /// Citation into a web-search result.
    #[serde(rename = "web_search_result_location")]
    WebSearchResult {
        /// Text cited by the model.
        cited_text: String,
        /// Opaque encrypted search-result index.
        encrypted_index: String,
        /// Title of the cited result, when available.
        #[serde(skip_serializing_if = "Option::is_none")]
        title: Option<String>,
        /// URL of the cited result.
        url: String,
    },
    /// Citation into a request `search_result` block.
    #[serde(rename = "search_result_location")]
    SearchResult {
        /// Text cited by the model.
        cited_text: String,
        /// End content-block index inside the search result.
        end_block_index: u32,
        /// Zero-based index of the cited search-result block in the request.
        search_result_index: u32,
        /// Source URL or identifier for the cited search result.
        source: String,
        /// Start content-block index inside the search result.
        start_block_index: u32,
        /// Title of the cited result, when available.
        #[serde(skip_serializing_if = "Option::is_none")]
        title: Option<String>,
    },
}

impl TextCitationParam {
    /// Creates a character-location citation.
    pub fn char_location(
        cited_text: impl Into<String>,
        document_index: u32,
        start_char_index: u32,
        end_char_index: u32,
    ) -> Self {
        Self::Char {
            cited_text: cited_text.into(),
            document_index,
            document_title: None,
            end_char_index,
            start_char_index,
        }
    }

    /// Creates a page-location citation.
    pub fn page_location(
        cited_text: impl Into<String>,
        document_index: u32,
        start_page_number: u32,
        end_page_number: u32,
    ) -> Self {
        Self::Page {
            cited_text: cited_text.into(),
            document_index,
            document_title: None,
            end_page_number,
            start_page_number,
        }
    }

    /// Creates a content-block-location citation.
    pub fn content_block_location(
        cited_text: impl Into<String>,
        document_index: u32,
        start_block_index: u32,
        end_block_index: u32,
    ) -> Self {
        Self::ContentBlock {
            cited_text: cited_text.into(),
            document_index,
            document_title: None,
            end_block_index,
            start_block_index,
        }
    }

    /// Creates a web-search-result citation.
    pub fn web_search_result_location(
        cited_text: impl Into<String>,
        encrypted_index: impl Into<String>,
        url: impl Into<String>,
    ) -> Self {
        Self::WebSearchResult {
            cited_text: cited_text.into(),
            encrypted_index: encrypted_index.into(),
            title: None,
            url: url.into(),
        }
    }

    /// Creates a search-result citation.
    pub fn search_result_location(
        cited_text: impl Into<String>,
        search_result_index: u32,
        source: impl Into<String>,
        start_block_index: u32,
        end_block_index: u32,
    ) -> Self {
        Self::SearchResult {
            cited_text: cited_text.into(),
            end_block_index,
            search_result_index,
            source: source.into(),
            start_block_index,
            title: None,
        }
    }

    /// Sets a document title on document-backed citation variants.
    pub fn with_document_title(self, document_title: impl Into<String>) -> Self {
        let document_title = Some(document_title.into());
        match self {
            Self::Char {
                cited_text,
                document_index,
                end_char_index,
                start_char_index,
                ..
            } => Self::Char {
                cited_text,
                document_index,
                document_title,
                end_char_index,
                start_char_index,
            },
            Self::Page {
                cited_text,
                document_index,
                end_page_number,
                start_page_number,
                ..
            } => Self::Page {
                cited_text,
                document_index,
                document_title,
                end_page_number,
                start_page_number,
            },
            Self::ContentBlock {
                cited_text,
                document_index,
                end_block_index,
                start_block_index,
                ..
            } => Self::ContentBlock {
                cited_text,
                document_index,
                document_title,
                end_block_index,
                start_block_index,
            },
            Self::WebSearchResult {
                cited_text,
                encrypted_index,
                title,
                url,
            } => Self::WebSearchResult {
                cited_text,
                encrypted_index,
                title,
                url,
            },
            Self::SearchResult {
                cited_text,
                end_block_index,
                search_result_index,
                source,
                start_block_index,
                title,
            } => Self::SearchResult {
                cited_text,
                end_block_index,
                search_result_index,
                source,
                start_block_index,
                title,
            },
        }
    }

    /// Sets a title on search-result citation variants.
    pub fn with_title(self, title: impl Into<String>) -> Self {
        let title = Some(title.into());
        match self {
            Self::WebSearchResult {
                cited_text,
                encrypted_index,
                url,
                ..
            } => Self::WebSearchResult {
                cited_text,
                encrypted_index,
                title,
                url,
            },
            Self::SearchResult {
                cited_text,
                end_block_index,
                search_result_index,
                source,
                start_block_index,
                ..
            } => Self::SearchResult {
                cited_text,
                end_block_index,
                search_result_index,
                source,
                start_block_index,
                title,
            },
            Self::Char {
                cited_text,
                document_index,
                document_title,
                end_char_index,
                start_char_index,
            } => Self::Char {
                cited_text,
                document_index,
                document_title,
                end_char_index,
                start_char_index,
            },
            Self::Page {
                cited_text,
                document_index,
                document_title,
                end_page_number,
                start_page_number,
            } => Self::Page {
                cited_text,
                document_index,
                document_title,
                end_page_number,
                start_page_number,
            },
            Self::ContentBlock {
                cited_text,
                document_index,
                document_title,
                end_block_index,
                start_block_index,
            } => Self::ContentBlock {
                cited_text,
                document_index,
                document_title,
                end_block_index,
                start_block_index,
            },
        }
    }
}

/// A request-side image source.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ImageSourceParam {
    /// Base64-encoded image bytes.
    Base64 {
        /// Image media type accepted by the API.
        media_type: String,
        /// Base64-encoded image bytes.
        data: String,
    },
    /// Image fetched from a URL by the API.
    Url {
        /// Image URL.
        url: String,
    },
}

impl ImageSourceParam {
    /// Creates a base64 image source.
    pub fn base64(media_type: impl Into<String>, data: impl Into<String>) -> Self {
        Self::Base64 {
            media_type: media_type.into(),
            data: data.into(),
        }
    }

    /// Creates a URL image source.
    pub fn url(url: impl Into<String>) -> Self {
        Self::Url { url: url.into() }
    }
}

/// A request-side document source.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum DocumentSourceParam {
    /// Base64-encoded PDF bytes.
    Base64 {
        /// PDF media type accepted by the API.
        media_type: DocumentMediaType,
        /// Base64-encoded PDF bytes.
        data: String,
    },
    /// Plain text document bytes.
    #[serde(rename = "text")]
    PlainText {
        /// Plain text media type accepted by the API.
        media_type: DocumentMediaType,
        /// Text document payload.
        data: String,
    },
    /// Document composed from text and image content blocks.
    Content {
        /// Content payload for the document.
        content: ContentBlockSourceContentParam,
    },
    /// PDF fetched from a URL by the API.
    Url {
        /// PDF URL.
        url: String,
    },
}

impl DocumentSourceParam {
    /// Creates a base64 PDF document source.
    pub fn base64_pdf(data: impl Into<String>) -> Self {
        Self::Base64 {
            media_type: DocumentMediaType::ApplicationPdf,
            data: data.into(),
        }
    }

    /// Creates a plain text document source.
    pub fn plain_text(data: impl Into<String>) -> Self {
        Self::PlainText {
            media_type: DocumentMediaType::TextPlain,
            data: data.into(),
        }
    }

    /// Creates a content document source.
    pub fn content(content: ContentBlockSourceContentParam) -> Self {
        Self::Content { content }
    }

    /// Creates a URL PDF document source.
    pub fn url_pdf(url: impl Into<String>) -> Self {
        Self::Url { url: url.into() }
    }
}

/// Media types accepted by stable document request sources.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DocumentMediaType {
    /// PDF document media type.
    #[serde(rename = "application/pdf")]
    ApplicationPdf,
    /// Plain text document media type.
    #[serde(rename = "text/plain")]
    TextPlain,
}

/// Content accepted by a `content` document source.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContentBlockSourceContentParam {
    /// Plain text content.
    Text(String),
    /// Structured text and image blocks.
    Blocks(Vec<ContentBlockSourceContentBlockParam>),
}

impl ContentBlockSourceContentParam {
    /// Creates a plain text content source.
    pub fn text(text: impl Into<String>) -> Self {
        Self::Text(text.into())
    }

    /// Creates structured content-source blocks.
    pub fn blocks(blocks: Vec<ContentBlockSourceContentBlockParam>) -> Self {
        Self::Blocks(blocks)
    }
}

/// A block accepted inside a `content` document source.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlockSourceContentBlockParam {
    /// Plain text content.
    Text {
        /// The UTF-8 text payload.
        text: String,
        /// Optional cache control marker for this text block.
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<CacheControl>,
    },
    /// Image content.
    Image {
        /// The image source.
        source: ImageSourceParam,
        /// Optional cache control marker for this image block.
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<CacheControl>,
    },
}

impl ContentBlockSourceContentBlockParam {
    /// Creates a text content-source block.
    pub fn text(text: impl Into<String>) -> Self {
        Self::Text {
            text: text.into(),
            cache_control: None,
        }
    }

    /// Creates a base64 image content-source block.
    pub fn image_base64(media_type: impl Into<String>, data: impl Into<String>) -> Self {
        Self::Image {
            source: ImageSourceParam::base64(media_type, data),
            cache_control: None,
        }
    }

    /// Creates a URL image content-source block.
    pub fn image_url(url: impl Into<String>) -> Self {
        Self::Image {
            source: ImageSourceParam::url(url),
            cache_control: None,
        }
    }

    /// Sets cache control on this content-source block.
    pub fn with_cache_control(self, cache_control: CacheControl) -> Self {
        match self {
            Self::Text { text, .. } => Self::Text {
                text,
                cache_control: Some(cache_control),
            },
            Self::Image { source, .. } => Self::Image {
                source,
                cache_control: Some(cache_control),
            },
        }
    }
}

/// Citation configuration accepted by request content blocks.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CitationsConfigParam {
    /// Whether citations should be enabled.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl CitationsConfigParam {
    /// Creates citation configuration with no fields set.
    pub fn new() -> Self {
        Self { enabled: None }
    }

    /// Creates citation configuration with an explicit enabled setting.
    pub fn enabled(enabled: bool) -> Self {
        Self {
            enabled: Some(enabled),
        }
    }
}

impl Default for CitationsConfigParam {
    fn default() -> Self {
        Self::new()
    }
}

/// Text block accepted inside a search result.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SearchResultTextBlockParam {
    /// Plain text search-result content.
    Text {
        /// The UTF-8 text payload.
        text: String,
        /// Optional cache control marker for this text block.
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<CacheControl>,
    },
}

impl SearchResultTextBlockParam {
    /// Creates a text search-result block.
    pub fn text(text: impl Into<String>) -> Self {
        Self::Text {
            text: text.into(),
            cache_control: None,
        }
    }

    /// Sets cache control on this search-result text block.
    pub fn with_cache_control(self, cache_control: CacheControl) -> Self {
        match self {
            Self::Text { text, .. } => Self::Text {
                text,
                cache_control: Some(cache_control),
            },
        }
    }
}

impl TryFrom<ContentBlock> for ContentBlockParam {
    type Error = ContentBlockParamConversionError;

    fn try_from(value: ContentBlock) -> Result<Self, Self::Error> {
        match value {
            ContentBlock::Text { text, citations } => Ok(Self::Text {
                text,
                citations: citations.map(|items| items.into_iter().map(Into::into).collect()),
                cache_control: None,
            }),
            ContentBlock::Thinking {
                thinking,
                signature,
            } => Ok(Self::Thinking {
                thinking,
                signature,
            }),
            ContentBlock::RedactedThinking { data } => Ok(Self::redacted_thinking(data)),
            ContentBlock::ToolUse { id, name, input } => {
                Self::tool_use(id, name, input).map_err(ContentBlockParamConversionError::ToolName)
            }
            ContentBlock::ToolResult { .. } => {
                Err(ContentBlockParamConversionError::UnsupportedContentBlock {
                    block_type: "tool_result",
                })
            }
        }
    }
}

impl TryFrom<&ContentBlock> for ContentBlockParam {
    type Error = ContentBlockParamConversionError;

    fn try_from(value: &ContentBlock) -> Result<Self, Self::Error> {
        match value {
            ContentBlock::Text { text, citations } => Ok(Self::Text {
                text: text.clone(),
                citations: citations
                    .clone()
                    .map(|items| items.into_iter().map(Into::into).collect()),
                cache_control: None,
            }),
            ContentBlock::Thinking {
                thinking,
                signature,
            } => Ok(Self::Thinking {
                thinking: thinking.clone(),
                signature: signature.clone(),
            }),
            ContentBlock::RedactedThinking { data } => Ok(Self::redacted_thinking(data.clone())),
            ContentBlock::ToolUse { id, name, input } => {
                Self::tool_use(id.clone(), name.as_str(), input.clone())
                    .map_err(ContentBlockParamConversionError::ToolName)
            }
            ContentBlock::ToolResult { .. } => {
                Err(ContentBlockParamConversionError::UnsupportedContentBlock {
                    block_type: "tool_result",
                })
            }
        }
    }
}

/// Errors produced while converting response content blocks into request blocks.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum ContentBlockParamConversionError {
    /// The response content block has no conservative request-side equivalent.
    #[error("content block type `{block_type}` cannot be converted to a request content block")]
    UnsupportedContentBlock {
        /// Wire `type` value of the unsupported content block.
        block_type: &'static str,
    },
    /// The response tool-use block contained an invalid tool name.
    #[error(transparent)]
    ToolName(#[from] ToolNameError),
}

/// Errors produced while adding cache control to request content blocks.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum ContentBlockParamCacheControlError {
    /// The stable Messages API does not expose cache control on this block type.
    #[error("content block type `{block_type}` does not support cache_control")]
    UnsupportedContentBlock {
        /// Wire `type` value of the unsupported content block.
        block_type: &'static str,
    },
}

/// Tool result content accepted by the Messages API.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ToolResultContent {
    /// A plain text tool result.
    Text(String),
    /// Structured tool result content blocks.
    Blocks(Vec<ContentBlockParam>),
}

impl ToolResultContent {
    /// Creates plain text tool result content.
    pub fn text(text: impl Into<String>) -> Self {
        Self::Text(text.into())
    }

    /// Creates structured tool result content.
    pub fn blocks(blocks: Vec<ContentBlockParam>) -> Self {
        Self::Blocks(blocks)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn content_block_deserializes_redacted_thinking() -> Result<(), Box<dyn std::error::Error>> {
        let block = serde_json::from_str::<ContentBlock>(
            r#"{"type":"redacted_thinking","data":"Redacted"}"#,
        )?;

        assert_eq!(block, ContentBlock::redacted_thinking("Redacted"));
        Ok(())
    }

    #[test]
    fn content_block_serializes_redacted_thinking() -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(ContentBlock::redacted_thinking("Redacted"))?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "redacted_thinking",
                "data": "Redacted"
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_serializes_thinking_with_signature()
    -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(ContentBlockParam::thinking_with_signature(
            "I should preserve this.",
            "ThinkingSignature",
        ))?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "thinking",
                "thinking": "I should preserve this.",
                "signature": "ThinkingSignature"
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_omits_absent_thinking_signature()
    -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(ContentBlockParam::thinking("Partial thinking"))?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "thinking",
                "thinking": "Partial thinking"
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_omits_absent_cache_control() -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(ContentBlockParam::text("Cache only when requested"))?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "text",
                "text": "Cache only when requested"
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_serializes_cache_control() -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(
            ContentBlockParam::text("Cache this block").with_cache_control(
                CacheControl::ephemeral_with_ttl(crate::CacheControlTtl::FiveMinutes),
            )?,
        )?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "text",
                "text": "Cache this block",
                "cache_control": {
                    "type": "ephemeral",
                    "ttl": "5m"
                }
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_serializes_text_citations() -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(ContentBlockParam::text_with_citations(
            "The report shows growth.",
            vec![
                TextCitationParam::char_location("growth", 0, 10, 16)
                    .with_document_title("Plain text report"),
                TextCitationParam::page_location("report", 1, 2, 3),
                TextCitationParam::content_block_location("inline chart", 2, 0, 1)
                    .with_document_title("Inline source"),
                TextCitationParam::web_search_result_location(
                    "public source",
                    "encrypted-index",
                    "https://example.com/source",
                )
                .with_title("Web result"),
                TextCitationParam::search_result_location(
                    "search excerpt",
                    0,
                    "https://example.com/search",
                    0,
                    2,
                )
                .with_title("Search result"),
            ],
        ))?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "text",
                "text": "The report shows growth.",
                "citations": [
                    {
                        "type": "char_location",
                        "cited_text": "growth",
                        "document_index": 0,
                        "document_title": "Plain text report",
                        "start_char_index": 10,
                        "end_char_index": 16
                    },
                    {
                        "type": "page_location",
                        "cited_text": "report",
                        "document_index": 1,
                        "start_page_number": 2,
                        "end_page_number": 3
                    },
                    {
                        "type": "content_block_location",
                        "cited_text": "inline chart",
                        "document_index": 2,
                        "document_title": "Inline source",
                        "start_block_index": 0,
                        "end_block_index": 1
                    },
                    {
                        "type": "web_search_result_location",
                        "cited_text": "public source",
                        "encrypted_index": "encrypted-index",
                        "title": "Web result",
                        "url": "https://example.com/source"
                    },
                    {
                        "type": "search_result_location",
                        "cited_text": "search excerpt",
                        "search_result_index": 0,
                        "source": "https://example.com/search",
                        "start_block_index": 0,
                        "end_block_index": 2,
                        "title": "Search result"
                    }
                ]
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_text_citations_omit_optional_fields()
    -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(ContentBlockParam::text_with_citations(
            "Short answer.",
            vec![
                TextCitationParam::char_location("answer", 0, 0, 6),
                TextCitationParam::web_search_result_location(
                    "source",
                    "encrypted-index",
                    "https://example.com/source",
                ),
            ],
        ))?;

        let citations = value
            .get("citations")
            .and_then(serde_json::Value::as_array)
            .ok_or_else(|| std::io::Error::other("expected citations"))?;

        assert!(citations[0].get("document_title").is_none());
        assert!(citations[1].get("title").is_none());
        Ok(())
    }

    #[test]
    fn content_block_param_text_citations_survive_cache_control()
    -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(
            ContentBlockParam::text_with_citations(
                "Cache cited text.",
                vec![TextCitationParam::page_location("cited", 0, 1, 1)],
            )
            .with_cache_control(CacheControl::ephemeral())?,
        )?;

        assert!(value.get("citations").is_some());
        assert_eq!(
            value.get("cache_control"),
            Some(&serde_json::json!({ "type": "ephemeral" }))
        );
        Ok(())
    }

    #[test]
    fn content_block_deserializes_response_text_citations() -> Result<(), Box<dyn std::error::Error>>
    {
        let block = serde_json::from_str::<ContentBlock>(
            r#"{
                "type": "text",
                "text": "See the source.",
                "citations": [
                    {
                        "type": "page_location",
                        "cited_text": "source text",
                        "document_index": 0,
                        "document_title": null,
                        "start_page_number": 4,
                        "end_page_number": 5,
                        "file_id": "file_01"
                    }
                ]
            }"#,
        )?;

        assert_eq!(
            block,
            ContentBlock::Text {
                text: "See the source.".to_owned(),
                citations: Some(vec![TextCitation::Page {
                    cited_text: "source text".to_owned(),
                    document_index: 0,
                    document_title: None,
                    end_page_number: 5,
                    file_id: Some("file_01".to_owned()),
                    start_page_number: 4,
                }]),
            }
        );
        Ok(())
    }

    #[test]
    fn content_block_param_serializes_url_image() -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(ContentBlockParam::image_url(
            "https://example.com/image.png",
        ))?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "image",
                "source": {
                    "type": "url",
                    "url": "https://example.com/image.png"
                }
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_base64_image_serialization_is_unchanged()
    -> Result<(), Box<dyn std::error::Error>> {
        let value =
            serde_json::to_value(ContentBlockParam::image_base64("image/png", "base64-image"))?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": "image/png",
                    "data": "base64-image"
                }
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_serializes_document_sources() -> Result<(), Box<dyn std::error::Error>> {
        let blocks = [
            ContentBlockParam::document_base64_pdf("base64-pdf"),
            ContentBlockParam::document_text("Plain document text"),
            ContentBlockParam::document_url("https://example.com/file.pdf"),
            ContentBlockParam::document_content(ContentBlockSourceContentParam::blocks(vec![
                ContentBlockSourceContentBlockParam::text("intro"),
                ContentBlockSourceContentBlockParam::image_url("https://example.com/chart.png"),
            ])),
        ];

        let value = serde_json::to_value(blocks)?;

        assert_eq!(
            value,
            serde_json::json!([
                {
                    "type": "document",
                    "source": {
                        "type": "base64",
                        "media_type": "application/pdf",
                        "data": "base64-pdf"
                    }
                },
                {
                    "type": "document",
                    "source": {
                        "type": "text",
                        "media_type": "text/plain",
                        "data": "Plain document text"
                    }
                },
                {
                    "type": "document",
                    "source": {
                        "type": "url",
                        "url": "https://example.com/file.pdf"
                    }
                },
                {
                    "type": "document",
                    "source": {
                        "type": "content",
                        "content": [
                            {
                                "type": "text",
                                "text": "intro"
                            },
                            {
                                "type": "image",
                                "source": {
                                    "type": "url",
                                    "url": "https://example.com/chart.png"
                                }
                            }
                        ]
                    }
                }
            ])
        );
        Ok(())
    }

    #[test]
    fn content_block_param_document_omits_optional_fields() -> Result<(), Box<dyn std::error::Error>>
    {
        let value = serde_json::to_value(ContentBlockParam::document_text("Plain document text"))?;

        assert!(value.get("title").is_none());
        assert!(value.get("context").is_none());
        assert!(value.get("citations").is_none());
        assert!(value.get("cache_control").is_none());
        Ok(())
    }

    #[test]
    fn content_block_param_serializes_document_optional_fields_and_cache_control()
    -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(ContentBlockParam::Document {
            source: DocumentSourceParam::url_pdf("https://example.com/file.pdf"),
            title: Some("Quarterly report".to_owned()),
            context: Some("Use the revenue section.".to_owned()),
            citations: Some(CitationsConfigParam::enabled(true)),
            cache_control: Some(CacheControl::ephemeral_with_ttl(
                crate::CacheControlTtl::OneHour,
            )),
        })?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "document",
                "source": {
                    "type": "url",
                    "url": "https://example.com/file.pdf"
                },
                "title": "Quarterly report",
                "context": "Use the revenue section.",
                "citations": {
                    "enabled": true
                },
                "cache_control": {
                    "type": "ephemeral",
                    "ttl": "1h"
                }
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_serializes_search_result() -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(ContentBlockParam::search_result(
            vec![SearchResultTextBlockParam::text("Result excerpt")],
            "https://example.com/result",
            "Example result",
        ))?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "search_result",
                "content": [
                    {
                        "type": "text",
                        "text": "Result excerpt"
                    }
                ],
                "source": "https://example.com/result",
                "title": "Example result"
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_search_result_omits_optional_fields()
    -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(ContentBlockParam::search_result(
            vec![SearchResultTextBlockParam::text("Result excerpt")],
            "https://example.com/result",
            "Example result",
        ))?;

        assert!(value.get("citations").is_none());
        assert!(value.get("cache_control").is_none());
        Ok(())
    }

    #[test]
    fn content_block_param_serializes_search_result_cache_control()
    -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(
            ContentBlockParam::search_result(
                vec![
                    SearchResultTextBlockParam::text("Result excerpt")
                        .with_cache_control(CacheControl::ephemeral()),
                ],
                "https://example.com/result",
                "Example result",
            )
            .with_cache_control(CacheControl::ephemeral_with_ttl(
                crate::CacheControlTtl::FiveMinutes,
            ))?,
        )?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "search_result",
                "content": [
                    {
                        "type": "text",
                        "text": "Result excerpt",
                        "cache_control": {
                            "type": "ephemeral"
                        }
                    }
                ],
                "source": "https://example.com/result",
                "title": "Example result",
                "cache_control": {
                    "type": "ephemeral",
                    "ttl": "5m"
                }
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_rejects_cache_control_on_thinking() {
        let result = ContentBlockParam::thinking("Thinking is not cache-marked")
            .with_cache_control(CacheControl::ephemeral());

        assert_eq!(
            result,
            Err(
                ContentBlockParamCacheControlError::UnsupportedContentBlock {
                    block_type: "thinking"
                }
            )
        );
    }

    #[test]
    fn content_block_param_serializes_redacted_thinking() -> Result<(), Box<dyn std::error::Error>>
    {
        let value = serde_json::to_value(ContentBlockParam::redacted_thinking("Redacted"))?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "redacted_thinking",
                "data": "Redacted"
            })
        );
        Ok(())
    }

    #[test]
    fn content_block_param_deserializes_thinking_and_redacted_thinking()
    -> Result<(), Box<dyn std::error::Error>> {
        let thinking = serde_json::from_str::<ContentBlockParam>(
            r#"{"type":"thinking","thinking":"I should preserve this.","signature":"ThinkingSignature"}"#,
        )?;
        let redacted = serde_json::from_str::<ContentBlockParam>(
            r#"{"type":"redacted_thinking","data":"Redacted"}"#,
        )?;

        assert_eq!(
            thinking,
            ContentBlockParam::thinking_with_signature(
                "I should preserve this.",
                "ThinkingSignature"
            )
        );
        assert_eq!(redacted, ContentBlockParam::redacted_thinking("Redacted"));
        Ok(())
    }

    #[test]
    fn content_block_param_serializes_tool_use() -> Result<(), Box<dyn std::error::Error>> {
        let value = serde_json::to_value(ContentBlockParam::tool_use(
            "toolu_01",
            "get_weather",
            serde_json::json!({ "city": "London" }),
        )?)?;

        assert_eq!(
            value,
            serde_json::json!({
                "type": "tool_use",
                "id": "toolu_01",
                "name": "get_weather",
                "input": { "city": "London" }
            })
        );
        Ok(())
    }

    #[test]
    fn response_content_blocks_convert_to_request_blocks() -> Result<(), Box<dyn std::error::Error>>
    {
        let blocks = [
            ContentBlock::text("Hello"),
            ContentBlock::Thinking {
                thinking: "I should preserve this.".to_owned(),
                signature: Some("ThinkingSignature".to_owned()),
            },
            ContentBlock::redacted_thinking("RedactedPayload"),
            ContentBlock::ToolUse {
                id: "toolu_01".to_owned(),
                name: "get_weather".to_owned(),
                input: serde_json::json!({ "city": "London" }),
            },
        ];

        let params = blocks
            .iter()
            .map(ContentBlockParam::try_from)
            .collect::<Result<Vec<_>, _>>()?;

        assert_eq!(
            params,
            vec![
                ContentBlockParam::text("Hello"),
                ContentBlockParam::thinking_with_signature(
                    "I should preserve this.",
                    "ThinkingSignature"
                ),
                ContentBlockParam::redacted_thinking("RedactedPayload"),
                ContentBlockParam::tool_use(
                    "toolu_01",
                    "get_weather",
                    serde_json::json!({ "city": "London" })
                )?,
            ]
        );
        Ok(())
    }

    #[test]
    fn response_text_citations_convert_to_request_citations()
    -> Result<(), Box<dyn std::error::Error>> {
        let param = ContentBlockParam::try_from(ContentBlock::Text {
            text: "See source.".to_owned(),
            citations: Some(vec![TextCitation::Char {
                cited_text: "source".to_owned(),
                document_index: 0,
                document_title: Some("Source doc".to_owned()),
                end_char_index: 12,
                file_id: Some("file_01".to_owned()),
                start_char_index: 6,
            }]),
        })?;

        assert_eq!(
            param,
            ContentBlockParam::text_with_citations(
                "See source.",
                vec![
                    TextCitationParam::char_location("source", 0, 6, 12)
                        .with_document_title("Source doc")
                ],
            )
        );
        Ok(())
    }

    #[test]
    fn response_tool_result_conversion_is_explicitly_unsupported() {
        let error = ContentBlockParam::try_from(ContentBlock::ToolResult {
            tool_use_id: "toolu_01".to_owned(),
            content: vec![ContentBlock::text("result")],
        });

        assert_eq!(
            error,
            Err(ContentBlockParamConversionError::UnsupportedContentBlock {
                block_type: "tool_result"
            })
        );
    }
}
